Repository GuyKh/iec-custom-component, pull requests merged in 2024-08, with the labels that each got.

#134 TYPO
  custom_components/iec/translations/he.json
Labels: Review effort [1-5]: 1, Bug fix

#136 Fix url in ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, Review effort [1-5]: 1

#133 feat: A better predicted estimated cost
  custom_components/iec/const.py
  custom_components/iec/coordinator.py
  custom_components/iec/manifest.json
  custom_components/iec/sensor.py
  custom_components/iec/translations/en.json
  custom_components/iec/translations/he.json
  requirements.txt
Labels: enhancement

#139 fix: Fix Custom Attribues value fetching
  custom_components/iec/manifest.json
  custom_components/iec/sensor.py
Labels: Bug fix

#147 fix bad str to int conversion
  custom_components/iec/coordinator.py
Labels: bug_fix

#151 fix: Fix no response on DevicesById in cost estimation flow
  custom_components/iec/coordinator.py
  custom_components/iec/manifest.json
Labels: Bug fix

#152 fix: last_meter_read is not defined
  custom_components/iec/coordinator.py
  custom_components/iec/manifest.json
Labels: Bug fix
